/*
 * build-guide.js — generate the lab guide FROM the step bundle.
 *
 * The guide and Rocky must never disagree: a learner who reads one thing and is shown
 * another loses trust in both. So the markdown is generated from the same bundle the
 * extension runs, and regenerated whenever the bundle changes. Rocky's step text becomes
 * the instruction; his authored WHY / WHAT / TIP become the prose underneath.
 *
 * Usage: node build-guide.js [bundle.json] [outDir]
 */
'use strict';
const fs = require('fs');
const path = require('path');

const bundlePath = process.argv[2] || path.join(__dirname, '..', 'vmpackage', 'webext', 'bundle', 'test-bundle.json');
const outDir = process.argv[3] || path.join(__dirname, 'lab-guide', 'Lab-Guide');

const b = JSON.parse(fs.readFileSync(bundlePath, 'utf8'));
fs.mkdirSync(outDir, { recursive: true });

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const files = [];

// Exercise 1 is hand-written (it carries the lab's introduction), so start at task 2 unless
// the bundle has only one task.
const tasks = (b.labs || []).flatMap((l) => l.tasks || []);
tasks.forEach((task, i) => {
  const n = i + 1;
  if (n === 1 && fs.existsSync(path.join(outDir, 'Task-1-Provision.md'))) {
    files.push('Task-1-Provision.md');
    return;
  }
  const title = (task.title || `Task ${n}`).replace(/^Task \d+:\s*/, '');
  const name = `Task-${n}-${slug(title).split('-').slice(0, 3).join('-')}.md`;
  const L = [];
  L.push(`# Exercise ${n}: ${title}`);
  L.push('');
  L.push(`**Time:** about ${Math.max(3, Math.round((task.steps || []).length * 1.2))} minutes`);
  L.push('');
  L.push('> Rocky glows each control as you reach it. Everything he says is written here too.');
  L.push('');
  L.push('---');
  L.push('');

  (task.steps || []).forEach((s, j) => {
    L.push(`## Step ${j + 1} — ${s.text}`);
    L.push('');
    if (s.value && s.value.display) {
      L.push(`Value to enter: \`${s.value.display}\``);
      L.push('');
      L.push('Rocky copies this to your clipboard, so you can paste it.');
      L.push('');
    }
    if (s.surface === 'vision') {
      L.push('> This step happens in a Windows dialog, not the web page.');
      L.push('');
    }
    const learn = s.learn || {};
    if (learn.why) { L.push(`**Why this matters.** ${learn.why}`); L.push(''); }
    if (learn.what) { L.push(`**What this is.** ${learn.what}`); L.push(''); }
    if (learn.tip) { L.push(`**Tip.** ${learn.tip}`); L.push(''); }
  });

  L.push('---');
  L.push('');
  L.push(n === tasks.length
    ? '**You are done.** You deployed a real model and had a real conversation with it. Rocky guided every click, and told you why each one mattered.'
    : `**Checkpoint:** exercise ${n} complete. Continue to exercise ${n + 1}.`);
  L.push('');

  fs.writeFileSync(path.join(outDir, name), L.join('\n'), 'utf8');
  files.push(name);
  console.log(`  wrote ${name} (${(task.steps || []).length} steps)`);
});

// masterdoc.json: the ordered list CloudLabs renders. Raw GitHub URLs are filled in by the
// publisher; keeping them relative here means the repo is the single source of order.
const master = {
  _comment: 'Generated by build-guide.js from the step bundle. Replace RAW_BASE with the raw.githubusercontent.com base for this repo/branch before uploading to CloudLabs.',
  title: b.title || 'Guided lab',
  files: files.map((f) => `RAW_BASE/LabGuidePackage/Lab Guide/${f}`),
};
fs.writeFileSync(path.join(outDir, 'masterdoc.json'), JSON.stringify(master, null, 2), 'utf8');
console.log(`  wrote masterdoc.json (${files.length} pages, in order)`);
console.log(`\nGuide generated from ${path.basename(bundlePath)} — guide and Rocky cannot drift.`);
